Update README.md
uptane/uptane-standard pull request #263
Opened 2023-11-13 16:03 UTC by JustinCappos

Fixes #262

2023-11-13 17:03 UTC, mnm678 approved these changes, later dismissed

2023-11-17 17:47 UTC, hexsecs commented on README.md
>  * [Uptane POUF (Protocols, Operations, Usage, and Formats) Guidelines](https://uptane.github.io/pouf.html)
```suggestion
* [Uptane POUF (Protocols, Operations, Usage, and Formats) Guidelines](https://uptane.org/docs/enhancements/pouf/pouf-main)
```

2023-11-17 17:48 UTC, hexsecs commented on README.md
>  * [Example POUF](https://uptane.github.io/reference_pouf.html)
```suggestion
* [Example POUF](https://uptane.org/docs/enhancements/pouf/pouf1)
```

2023-11-17 17:50 UTC, hexsecs requested changes
There were a few other broken links. I added suggested fixes for them.

2024-01-16 15:53 UTC, hexsecs commented
After some changes on the uptane.org site, there are still some broken links that need to be fixed.

2024-02-27 15:44 UTC, tkfu commented
All outstanding fixes have been applied.

2024-02-27 15:44 UTC, tkfu approved these changes

2024-02-27 15:47 UTC, hexsecs approved these changes

2024-02-27 15:47 UTC, merged